# Generated by Django 4.2.16 on 2024-09-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id_flashcard', models.IntegerField(primary_key=True, serialize=False)),
                ('front', models.CharField(max_length=30)),
                ('back', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_topic', models.IntegerField(primary_key=True, serialize=False)),
                ('name_topic', models.CharField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id_prodess', models.IntegerField(primary_key=True, serialize=False)),
                ('time_login', models.DateField()),
                ('number_time_study', models.DurationField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
